spring:
  application:
    name: AGENIN_TRANSACTION
    version: 1.0.0

  banner:
    location: classpath:/banner-text.txt

  # FIX: datasource not dataSource
  datasource:
    url: jdbc:postgresql://${AGENIN_DB_HOST}:${AGENIN_DB_PORT}/${AGENIN_DB_NAME}
    username: ${AGENIN_DB_USERNAME}
    password: ${AGENIN_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

  # Redis Configuration
  data:
    redis:
      host: ${AGENIN_REDIS_HOST}
      port: ${AGENIN_REDIS_PORT}
      password: ${AGENIN_REDIS_PASSWORD}
      timeout: 60s
      connect-timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 10s
          time-between-eviction-runs: 60s
        shutdown-timeout: 100ms

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000ms
      cache-null-values: false
      enable-statistics: true

  # KAFKA CONFIGURATION
  kafka:
    bootstrap-servers: ${AGENIN_BOOTSTRAP_KFK_SERVER}
    consumer:
      acks: all
      retries: 10
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        linger.ms: 10
        compression.type: lz4
        batch.size: 32768
        spring.json.add.type.headers: false
        spring:
          deserializer:
            key:
              delegate:
                class: org.springframework.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.common.serialization.StringDeserializer
        # KAFKA TRUSTED PACKAGES FOR JSON DESERIALIZATION
        json:
          trusted:
            packages: "*"
          value:
            default-type: com.jdt16.agenin.transaction.dto.response.RestApiResponse

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    redis:
      enabled: true
    db:
      enabled: true

# LOGGING
logging:
  level:
    root: INFO
    com.jdt16.agenin.transaction: DEBUG
    org:
      springframework:
        kafka: INFO
        cache: DEBUG
      apache:
        kafka: INFO

# REQUEST TOPIC
request-topic:
  create-transaction-topic: create-transaction-po
  create-log-topic: create-log-po

# KAFKA CONNECTOR
connector:
  environment: ${AGENIN_CONNECTOR_KFK_ENV}
  kafka:
    bootstrap-servers: ${AGENIN_BOOTSTRAP_KFK_SERVER}
    consumer-group: ${AGENIN_CONSUMER_GROUP}

server:
  port: 8282
